version: '3.8'

services:
  api:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

#se utiliza para persistir los datos de la base de datos PostgreSQL
volumes:
  pg_data: